name: Regios
main: net.jzx7.regios.RegiosPlugin
version: 5.9.8
authors: [johnnyzerox7, Adamki11s]
commands:
  regios:
    aliases: [reg, r]
    description: Use /regios help <Page Number>
    usage: Use /regios help for help.